FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY services/api/package.json services/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN npm ci --omit=dev --workspace services/api --include-workspace-root=false

COPY services/api ./services/api

EXPOSE 4000

CMD ["npm", "run", "start", "-w", "services/api"]
